### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shimazaki-koji** [shimazaki-koji/protospace-33364#1]
＃URL
https://protospace-33364.herokuapp.com/

**Comment by kouhei-masuda** [comment]
@shimazaki-koji さん、ご提出ありがとうございます！
ご連絡が大変遅くなり申し訳ございません。
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・プロトタイプ投稿ページで必要な情報が入力されていない場合、下記のスクショのようなエラーが起きる
(本来は投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まる仕様です）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7
![スクリーンショット 2021-03-08 22 08 08](https://user-images.githubusercontent.com/53155744/110325532-cbd3cf00-805a-11eb-8578-51d35a952549.png)

**Comment by shimazaki-koji** [comment]
修正したので確認をお願いいたします。

**Comment by saitoreina** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
